name: cc1
recipe: symfony
config:
  webroot: public
  php: '8.0'
  composer_version: 2-latest
  via: apache:2.4
  xdebug: true

services:
  node:
    type: node:14
    globals:
      gulp-cli: "latest"
      yarn: "latest"

tooling:
  symfony:
    service: appserver
    description: Run Symfony commands
    cmd:
      - bin/console
  npm:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  theme:
    service: node
    description: "Start theme dev"
    cmd: npm run watch
